### ISSUE TITLE
git项目提示不是git项目

### ISSUE THREAD

**Issue by Veyhunk** [emjio/git-auto-commit#1]
![image](https://user-images.githubusercontent.com/21153513/136720865-d816439f-327d-4d22-bf33-9d815d6971cb.png)

**Comment by emjio** [comment]
你好，出现此bug 请检查当前打开的项目文件夹下面是否含有.git 文件夹，或尝试重新打开vscode窗口。如果情况没有解决，请补充你所使用的vscode版本和系统版本。

**Comment by Veyhunk** [comment]
这是一个正常使用中的项目，因为需要频繁提交代码，所以找到了您开发的扩展，代码仓库本身没问题， 也重启电脑、重启应用、单独打开项目而不是使用多文件夹的工作区

**Comment by emjio** [comment]
你好，本项目依据 ```git log``` 状态和 ```git worktree list``` 进行git 合法性验证，请补充此两条命令在项目路径中的执行结果。
