### ISSUE TITLE
bug - 不是一个git 项目

### ISSUE THREAD

**Issue by zhanghuizong** [emjio/git-auto-commit#24]
# 相关信息

```
node: v14.16.0
vcode: 1.61.2
system: win10
```

现象是, 家用笔记本打开 gitee 仓库 会提示该问题.  而公司笔记本并没提示该问题

**Comment by zhanghuizong** [comment]
请问 插件更新发布了吗..... 目前还是存在问题

**Comment by emjio** [comment]
bug 未复现。 请贴出发生该提示的项目地址

**Comment by zhanghuizong** [comment]
随便打开都可以的.

我使用下来发现不是必现.

**Comment by zhanghuizong** [comment]
**今天调试了一下代码**

发现问题如下:

![image](https://user-images.githubusercontent.com/4384876/146673353-17e3bb3c-d65e-404f-9185-c76d13a37344.png)

操作系统: windows 10

而windows的 `cd` 切换其它盘符路径有个特点

从 c 盘切换至 d.  需要先执行 : `d:`. 然后: `cd d:\workspaces\gitee\notebook`
