### ISSUE TITLE
windows 不会自动提交

### ISSUE THREAD

**Issue by zhanghuizong** [emjio/git-auto-commit#26]
https://github.com/emjio/git-auto-commit/issues/24

作者这个问题不修复了吗~

**Comment by emjio** [comment]
你好，你提的这个问题　在mac / windows / wsl 下均未复现。请提供更加具体的版本信息。
自动提交是定时执行　git commit 实现的。

**Comment by emjio** [comment]
请提供　
vscode 版本
git 版本
插件版本。
插件配置信息。

**Comment by zhanghuizong** [comment]
**VsCode版本**
![image](https://user-images.githubusercontent.com/4384876/152811339-dca62ded-bb75-4c2e-bc12-1d6ea0a0c97f.png)

**插件版本**
![image](https://user-images.githubusercontent.com/4384876/152811617-88cbbb00-a0a6-4c1a-ac9d-4345ebefaeaa.png)

**插件配置**
![image](https://user-images.githubusercontent.com/4384876/152811768-4d5d6c0e-a487-4bc9-b853-fc637db5a42b.png)

**系统版本**
![image](https://user-images.githubusercontent.com/4384876/152811869-629dae73-709c-4c29-8c20-70b17a3af56f.png)

**Comment by emjio** [comment]
感谢补充。本周将会release 新版本

**Comment by zhanghuizong** [comment]
vscode  插件市场  -- 推一下尼

**Comment by emjio** [comment]
@zhanghuizong 新版本发布了
