### ISSUE TITLE
疑问: this.$option.commitTimeInterval

### ISSUE THREAD

**Issue by zhanghuizong** [emjio/git-auto-commit#3]
![image](https://user-images.githubusercontent.com/4384876/137421821-3d462bd4-d5bd-4fe6-aa13-6867ac7a4bfe.png)

如果为 0 是不是可以不用启动倒计时模式呀~

**Comment by emjio** [comment]
你好，触发commit的时机是当项目文件被保存的时候。该插件主旨是为了帮助忘记提交代码的用户，但如果用户时刻在开发的状态下，立即触发也是不合理的。至少是当你停下之后。否则可能会出现。保存一下一个commit 。导致混乱。
